package IO;




import java.io.FileOutputStream;
import java.util.Date;

import com.itextpdf.text.Anchor;
import com.itextpdf.text.BadElementException;
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Chapter;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.List;
import com.itextpdf.text.ListItem;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.Section;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import com.itextpdf.text.*;
import com.itextpdf.text.pdf.*;



public class PDFGenerator {

    private String FILE = "c:/temp/FirstPdf.pdf";
    private Font catFont = new Font(Font.FontFamily.TIMES_ROMAN, 18, Font.BOLD);
    private Font redFont = new Font(Font.FontFamily.TIMES_ROMAN, 12, Font.NORMAL, BaseColor.RED);
    private Font subFont = new Font(Font.FontFamily.TIMES_ROMAN, 16, Font.BOLD);
    private Font smallBold = new Font(Font.FontFamily.TIMES_ROMAN, 12, Font.BOLD);
    private Font italicFont = new Font(Font.FontFamily.TIMES_ROMAN, 12, Font.BOLDITALIC);

//    private ProjectInformation information;
//
//    public PDFGenerator(ProjectInformation information){
//        this.information = information;
//    }


    public void writePDF(String filepath){
        try {
            Document document = new Document();
            PdfWriter writer = PdfWriter.getInstance(document, new FileOutputStream(filepath));
            writer.setBoxSize("art", new Rectangle(36, 54, 559, 788));
            // set header
            HeaderFooter event = new HeaderFooter();
            writer.setPageEvent(event);


            document.open();
            // metadata can be seen in the property-menu of the pdf file
            addMetaData(document);
            // adding title page
            addTitlePage(document, writer);

            // Start a new page
            document.newPage();
            // adding all chapters
            addGeneralProjectInformation(document, 1);
            addDataFormatsAndStandards(document, 2);
            addRolesAndResponsibilities(document, 3);
            addPoliciesForDataSharingAndPublicAccess(document, 4);
            addDisseminationMethods(document, 5);
            addDataStorageAndPreservation(document, 6);

            document.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }













    // iText allows to add metadata to the PDF which can be viewed in your Adobe Reader
    // under File -> Properties
    private void addMetaData(Document document) {
        document.addTitle("Data Management Plan");
        document.addSubject("Using data management tool 'The better one'");
        document.addKeywords("Java, PDF, iText");
        document.addAuthor("...");
        document.addCreator("...");
    }




    private void addTitlePage(Document document, PdfWriter writer) throws DocumentException {

        Paragraph title = new Paragraph();
        // centered text
        //title.setAlignment(Element.ALIGN_CENTER);
        // We add one empty line
        addEmptyLine(title, 5);
        // Lets write a big header with project name
        title.add(new Paragraph("PROJECT TITLE", catFont));

        addEmptyLine(title, 1);

        PdfContentByte cb = writer.getDirectContent();

        cb.setLineWidth(2.0f); // Make a bit thicker than 1.0 default
        cb.setGrayStroke(0.5f); // 1 = black, 0 = white
        cb.moveTo(500, 670);
        cb.lineTo(20, 670);
        cb.stroke();

        addEmptyLine(title, 1);
        // Will create: Report generated by: _name,
        title.add(new Paragraph("A Data Management Plan generated by the 'The better DMP Tool'", smallBold));
        addEmptyLine(title, 1);

        Paragraph upperPartTitle = new Paragraph();
        upperPartTitle.add(new Paragraph("Responsible project manager: " + " Judith Neukamm ", smallBold));
        upperPartTitle.add(new Paragraph("Affiliation: University of Tuebingen", smallBold));
        upperPartTitle.add(new Paragraph("Last modified: " + new Date(), smallBold));
        upperPartTitle.add(new Paragraph("Copyright: The amazing THREE", smallBold));
        addEmptyLine(upperPartTitle, 3);
        upperPartTitle.add(new Paragraph("Project Description ", smallBold));

        addEmptyLine(upperPartTitle, 8);

        upperPartTitle.add(new Paragraph("This data management plan was produced by the Data Management Tool ......", italicFont));

        document.add(title);
        document.add(upperPartTitle);

    }

    private void addDataFormatsAndStandards(Document document, int chapterNumber) throws DocumentException {

        Anchor anchor = new Anchor("Data collected, Formats and Standards", catFont);
        anchor.setName("Data");

        // Second parameter is the number of the chapter
        Chapter catPart = new Chapter(new Paragraph(anchor), chapterNumber);

        Paragraph subPara = new Paragraph("Subcategory 1", subFont);
        Section subCatPart = catPart.addSection(subPara);
        subCatPart.add(new Paragraph("Hello"));

        subPara = new Paragraph("Subcategory 2", subFont);
        subCatPart = catPart.addSection(subPara);
        subCatPart.add(new Paragraph("Paragraph 1"));
        subCatPart.add(new Paragraph("Paragraph 2"));
        subCatPart.add(new Paragraph("Paragraph 3"));

        // add a list
        createList(subCatPart);
        Paragraph paragraph = new Paragraph();
        addEmptyLine(paragraph, 5);
        subCatPart.add(paragraph);

        // add a table
        //createTable(subCatPart);

        // now add all this to the document
        document.add(catPart);


    }




    private void addRolesAndResponsibilities(Document document, int chapterNumber) throws DocumentException {
        Anchor anchor = new Anchor("Roles and Responsibilities", catFont);
        anchor.setName("Roles");

        // Second parameter is the number of the chapter
        Chapter catPart = new Chapter(new Paragraph(anchor), chapterNumber);
        Paragraph subPara = new Paragraph("Responsible persons", subFont);
        addEmptyLine(catPart, 1);
        Section subCatPart = catPart.addSection(subPara);

        subCatPart.add(new Paragraph("Data owners: "));
        subCatPart.add(new Paragraph("Data managers: "));
        subCatPart.add(new Paragraph("Data contributors: "));
        subCatPart.add(new Paragraph("Data researchers: "));



        // now add all this to the document
        document.add(catPart);


    }



    private void addPoliciesForDataSharingAndPublicAccess(Document document, int chapterNumber) throws DocumentException {
        Anchor anchor = new Anchor("Policies for Data Sharing and Public Access", catFont);
        anchor.setName("policies");

        // Second parameter is the number of the chapter
        Chapter catPart = new Chapter(new Paragraph(anchor), chapterNumber);
        Paragraph subPara = new Paragraph("Subcategory 1", subFont);
        Section subCatPart = catPart.addSection(subPara);
        subCatPart.add(new Paragraph("Hello"));

        subPara = new Paragraph("Subcategory", subFont);
        subCatPart = catPart.addSection(subPara);
        subCatPart.add(new Paragraph("This is a very important message"));

        // now add all this to the document
        document.add(catPart);


    }



    private void addDisseminationMethods(Document document, int chapterNumber) throws DocumentException {
        Anchor anchor = new Anchor("Dissemination Methods", catFont);
        anchor.setName("dissemination");

        // Second parameter is the number of the chapter
        Chapter catPart = new Chapter(new Paragraph(anchor), chapterNumber);
        Paragraph subPara = new Paragraph("Subcategory 1", subFont);
        Section subCatPart = catPart.addSection(subPara);
        subCatPart.add(new Paragraph("Hello"));

        subPara = new Paragraph("Subcategory", subFont);
        subCatPart = catPart.addSection(subPara);
        subCatPart.add(new Paragraph("This is a very important message"));

        // now add all this to the document
        document.add(catPart);


    }



    private void addDataStorageAndPreservation(Document document, int chapterNumber) throws DocumentException {
        Anchor anchor = new Anchor("Data Storage and Preservation", catFont);
        anchor.setName("dataStorage");

        // Second parameter is the number of the chapter
        Chapter catPart = new Chapter(new Paragraph(anchor), chapterNumber);
        Paragraph subPara = new Paragraph("Subcategory 1", subFont);
        Section subCatPart = catPart.addSection(subPara);
        subCatPart.add(new Paragraph("Hello"));

        subPara = new Paragraph("Subcategory", subFont);
        subCatPart = catPart.addSection(subPara);
        subCatPart.add(new Paragraph("This is a very important message blubb"));

        // now add all this to the document
        document.add(catPart);


    }

    private void addGeneralProjectInformation(Document document, int chapterNumber) throws DocumentException {
        Anchor anchor = new Anchor("General project information", catFont);
        anchor.setName("information");

        // Second parameter is the number of the chapter
        Chapter catPart = new Chapter(new Paragraph(anchor), chapterNumber);
        addEmptyLine(catPart, 1);
        Paragraph subPara = new Paragraph("Project information", subFont);
        addEmptyLine(catPart, 1);
        Section subCatPart = catPart.addSection(subPara);

        subCatPart.add(new Paragraph("Species: ...." + " (NCBI ID: " + "...." + " )"));
        subCatPart.add(new Paragraph("Number of individuals: "));
        subCatPart.add(new Paragraph("Sample types: "));


        subPara = new Paragraph("Contact", subFont);
        subCatPart = catPart.addSection(subPara);
        subCatPart.add(new Paragraph("Name : \t" ));
        subCatPart.add(new Paragraph("Phone : \t" ));
        subCatPart.add(new Paragraph("Email: \t" ));
        // now add all this to the document
        document.add(catPart);


    }



    private void createTable(Section subCatPart) throws BadElementException {
        PdfPTable table = new PdfPTable(3);

        // t.setBorderColor(BaseColor.GRAY);
        // t.setPadding(4);
        // t.setSpacing(4);
        // t.setBorderWidth(1);

        PdfPCell c1 = new PdfPCell(new Phrase("Table Header 1"));
        c1.setHorizontalAlignment(Element.ALIGN_CENTER);
        table.addCell(c1);

        c1 = new PdfPCell(new Phrase("Table Header 2"));
        c1.setHorizontalAlignment(Element.ALIGN_CENTER);
        table.addCell(c1);

        c1 = new PdfPCell(new Phrase("Table Header 3"));
        c1.setHorizontalAlignment(Element.ALIGN_CENTER);
        table.addCell(c1);
        table.setHeaderRows(1);

        table.addCell("1.0");
        table.addCell("1.1");
        table.addCell("1.2");
        table.addCell("2.1");
        table.addCell("2.2");
        table.addCell("2.3");

        subCatPart.add(table);

    }

    private void createList(Section subCatPart) {
        List list = new List(true, false, 10);
        list.add(new ListItem("First point"));
        list.add(new ListItem("Second point"));
        list.add(new ListItem("Third point"));
        subCatPart.add(list);
    }

    private void addEmptyLine(Paragraph paragraph, int number) {
        for (int i = 0; i < number; i++) {
            paragraph.add(new Paragraph(" "));
        }
    }

    private void addEmptyLine(Chapter chapter, int number) {
        for (int i = 0; i < number; i++) {
            chapter.add(new Paragraph(" "));
        }
    }



    /** Inner class to add a header and a footer. */
    static class HeaderFooter extends PdfPageEventHelper {

        public void onEndPage (PdfWriter writer, Document document) {
            Rectangle rect = writer.getBoxSize("art");

            ColumnText.showTextAligned(writer.getDirectContent(),
                    Element.ALIGN_CENTER, new Phrase(String.format("page %d", writer.getPageNumber())),
                    (rect.getLeft() + rect.getRight()) / 2, rect.getBottom() - 18, 0);
        }
    }

}